Sprint 1/step 1
amon-dey/react-burger pull request #1
Opened 2024-12-15 13:40 UTC by amon-dey

что-то такое

2024-12-15 15:35 UTC, SergeyK2004 requested changes
Здравствуйте. 

Вы проделали большую работу, что мне понравилось:

Хорошо выполнена верстка
Использование атрибута key, и здорово, что для него вы используете уникальный _id, а не индекс массива.

но есть некоторые недочеты:

* Компонент App вместе с модулем стилей необходимо переместить в папку App в components
* https://disk.yandex.ru/d/jHICRHfzosnoAg Обратите внимание, что иконка неактивного пункта меню так-же должна быть не активной
* В верхней булке нужно добавлять текст `верх`, а в нижней - `низ`. Сверьтесь пожалуйста с макетом.
* Верхняя и нижняя булки должны быть всегда одинаковыми по заданию и у них должна быть иконка Замочек, так как их нельзя будет удалять (только заменять перетаскиванием)
* Тип для ингредиента повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу IngredientType в отдельный файл types.js в папку utils и импортировать туда, где нужно
* Каждой картинке (тегу img) нужен информативный атрибут alt
* Инлайн-стилей style={{не должно быть в проекте, если они не меняются динамически в коде компонента. Это затрудняет управление стилями. Все стили описываются в модульных .module.css файлах, а в коде компонентов используются модульные css-стили.

Исправьте указанные недочеты и присылайте работу на повторную проверку.

2024-12-15 15:35 UTC, SergeyK2004 commented on src/components/BurgerIngredients/BurgerIngredientsItem/index.tsx
> +                <img className="m-1" src={props.item.image}></img>
Каждой картинке (тегу img) нужен информативный атрибут alt

2024-12-15 15:35 UTC, SergeyK2004 commented on src/App.tsx
> +        <AppCard>
Компонентам не нужна лишняя обертка, в которой только добавляется дополнительный div
Вам нужно указать тег section внутри BurgerIngredients и BurgerConstructor, чтобы код стал семантически правильным. И это очистит код App от лишних несемантических div

Тут получится вот такой код в конце:

```jsx
  return (
    <>
      <AppHeader />
      <main className={appStyles.row}>
        <BurgerIngredients tabs={Tabs} data={burgerData} />
        <BurgerConstructor data={burgerData} />
      </main>
    </>
  );
```

2024-12-15 15:35 UTC, SergeyK2004 commented on src/App.tsx
> +      <nav>
Тег следует перенести внутрь компонента AppHeader, за навигационное меню отвечает сам компонент.

2024-12-15 15:35 UTC, SergeyK2004 commented on src/components/BurgerIngredients/index.tsx
> +            <div style={{ display: 'flex' }} className='mb-10'>
Инлайн-стилей `style={{` не должно быть в проекте, если они не меняются динамически в коде компонента. Это затрудняет управление стилями. Все стили описываются в модульных .module.css файлах, а в коде компонентов используются модульные css-стили.

2024-12-15 15:35 UTC, SergeyK2004 commented on src/components/BurgerIngredients/index.tsx
> +        PropTypes.shape({
Не стоит копировать тип такого сложного объекта. Если вы уже типизируете сразу приложение с помощью TS, то используйте созданный тип. (он у вас уже указан в 12 строке)

2024-12-15 15:35 UTC, SergeyK2004 commented on src/utils/data.tsx
> +export type Ingredient = {
Типы используемые в приложении следует перенести в файл types.ts
Модуль data пердназначен для хранения данных

2024-12-15 15:35 UTC, SergeyK2004 commented on src/components/BurgerIngredients/BurgerIngredientsGroup/index.tsx
> +                        <BurgerIngredientsItem item={item} ></BurgerIngredientsItem>
**Можно лучше:**

<BurgerIngredientsItem></BurgerIngredientsItem> 

Можно использовать самозакрывающиеся теги, если нет children (нет ничего между открывающим и закрывающим тегами ><).

2024-12-15 15:35 UTC, SergeyK2004 commented on src/components/BurgerConstructor/index.tsx
> +                            key={item._id}
Обратите внимание, что в последствии будет возможность добавлять один и тот-же ингредиент несколько раз и тогда _id не будет уникальным в этом массиве. Ингредиентам в конструкторе нужно будет добавлять свой id d будущем.

2024-12-15 16:53 UTC, amon-dey commented on src/components/BurgerIngredients/BurgerIngredientsItem/index.tsx
> +                <img className="m-1" src={props.item.image}></img>
fix https://github.com/amon-dey/react-burger/commit/431c0ae1524cfdb626421e85455cf4adf7b70538

2024-12-15 17:05 UTC, amon-dey commented on src/components/BurgerIngredients/index.tsx
> +            <div style={{ display: 'flex' }} className='mb-10'>
fixded by bb240992473abf7bd535948d4923069e820fc9f2

2024-12-15 17:13 UTC, amon-dey commented on src/utils/data.tsx
> +export type Ingredient = {
fixed by ee2895884a1a725f6077f61b443e444c428deb9e

2024-12-15 17:20 UTC, amon-dey commented on src/components/BurgerIngredients/BurgerIngredientsGroup/index.tsx
> +                        <BurgerIngredientsItem item={item} ></BurgerIngredientsItem>
fixed by 6c3da471edf8c292abd6c034d05972b9679fe586

2024-12-16 10:57 UTC, amon-dey commented on src/App.tsx
> +        <AppCard>
fix by 61f1c993066d97b7094f15e97b372f6b9c11f6c9

2024-12-16 10:57 UTC, amon-dey commented on src/components/BurgerIngredients/index.tsx
> +        PropTypes.shape({
fix by 61f1c993066d97b7094f15e97b372f6b9c11f6c9
хотя не знаю - не умею пока

2024-12-16 11:41 UTC, closed without merging